version: '3.7'
services:
  django:
    build:
      context: .
      dockerfile: Dockerfile.django
    image: diana33/lab4:compose-django
    container_name: compose-django
    ports:
      - 8000:8000
  monitoring:
    build:
      context: .
      dockerfile: Dockerfile.monitoring
    image: diana33/lab4:compose-monitoring
    container_name: compose-monitoring
    network_mode: "host"
